config/routes.rb
Rails.application.routes.draw do

resources :contacts

root 'staticpages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def destroy
    Contact.find(params[:id]).destroy
    redirect_to contacts_path
  end
      
  private

  def contact_params
    params.require(:contact).permit(:name, :age, :phone, :email, :friend)
  end
  
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :friend %>
  <%= f.check_box :friend %>

  <%= f.submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= render 'form.html.erb' %>

app/views/contacts/index.html.erb
<h1> All of your Contacts </h1>
<h4> Click on a name to see the contact in detail </h4>
<h5> <%= link_to 'Create New', new_contact_path %> </h5>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Age</td>
      <td>Phone</td>
      <td>Email</td>
      <td>Friend?</td>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
  </thead>
  <tbody>
<% @contacts.each do |contact| %>
  <tr>
    <td> <%= link_to "#{contact.name}", contact_path(contact) %> </td>
    <td> <%= contact.age %> </td>
    <td> <%= contact.phone %> </td>
    <td> <%= contact.email %> </td>
    <td> <%= contact.friend %> </td>
    <td> <%= link_to 'Edit', edit_contact_path(contact) %> </td>
    <td> <%= link_to 'Delete', contact, method: :delete %> </td>
  </tr>
<% end %>
  </tbody>
  </table>

app/views/contacts/new.html.erb
<h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>
<h4>Age: <%= @contact.age %></h4>
<p>Phone: <%= @contact.phone %></p>
<p>Email: <%= @contact.email %></p>
<p>Friend: <%= @contact.friend %></p>
<br />
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'List all Contacts', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar.html.erb' %>
    <%= yield %>
  </body>
</html>

app/views/staticpages/home.html.erb
<h1> Andrew's Contacts </h1>

<p> I'm a contact list, nothing special, but I keep track of important contact info for you </p>

<p> Have you ever thought about the fact that I'm super important, but you never thank me? </p>